trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  displayName: 'Test Azure Service Connection'
  inputs:
    azureSubscription: 'sc-azure-terraform-dev'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "Azure connection successful"

      az account show \
        --query "{subscription:name, subscriptionId:id, tenantId:tenantId}" \
        -o table